version: 2
updates:
- package-ecosystem: npm
  directory: "/public"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: animadio
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.7
    - 4.0.8
    - 4.1.4
    - 4.1.5
    - 4.1.8
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tracy/tracy
    versions:
    - 2.8.2
